# Generated by Django 4.0 on 2023-03-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_subscriber_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='created_at',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='name',
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
