# Generated by Django 4.0 on 2023-03-27 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_subscriber_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
