# Generated by Django 4.0 on 2023-03-27 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
