# Generated by Django 4.0 on 2023-06-06 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
