# Generated by Django 4.0 on 2023-06-07 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_broker_photo_1_broker_photo_2_broker_photo_3_and_more'),
        ('pages', '0013_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='broker',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='broker.broker'),
        ),
    ]
