# Generated by Django 4.1.3 on 2022-12-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='message',
            field=models.TextField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='subject',
            field=models.CharField(default='SOME STRING', max_length=30),
        ),
    ]
