# Generated by Django 4.1.3 on 2022-12-29 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0002_enquiry_message_enquiry_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='mobile',
            new_name='phone',
        ),
    ]
