# Generated by Django 4.1.3 on 2023-01-24 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0004_enquiry_property_enquiry_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='user',
            new_name='user_id',
        ),
    ]
