# Generated by Django 4.0 on 2023-03-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0006_rename_user_id_enquiry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='subject',
            field=models.CharField(max_length=30),
        ),
    ]
