# Generated by Django 4.0 on 2023-03-15 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_property_bathrooms'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('enquiry', '0008_alter_enquiry_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
