# Generated by Django 4.1.3 on 2022-12-23 06:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0001_initial'),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='broker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='broker.broker'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='garage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='property',
            name='lot_size',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photos/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='property',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='photos/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='property',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to='photos/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='property',
            name='photo_4',
            field=models.ImageField(blank=True, upload_to='photos/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='property',
            name='photo_5',
            field=models.ImageField(blank=True, upload_to='photos/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='property',
            name='photo_6',
            field=models.ImageField(blank=True, upload_to='photos/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='property',
            name='photo_main',
            field=models.ImageField(default=1, upload_to='photos/%y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='sqft',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(),
        ),
    ]
