# Generated by Django 4.0 on 2023-03-13 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_bathrooms_property_bedrooms_property_broker_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='lot_size',
            new_name='plot_size',
        ),
    ]
