# Generated by Django 4.0 on 2023-03-15 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_broker_photo_1_broker_photo_2_broker_photo_3_and_more'),
        ('property', '0004_alter_property_bathrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.broker'),
        ),
    ]
