# Generated by Django 4.0 on 2023-04-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_alter_property_photo_1_alter_property_photo_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='list_date',
            field=models.DateTimeField(),
        ),
    ]
