# Generated by Django 4.0 on 2023-05-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_state_city_alter_property_city_alter_property_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
