# Generated by Django 4.0 on 2023-05-04 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_state_city_alter_property_city_alter_property_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.city'),
        ),
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.state'),
        ),
    ]
