# Generated by Django 4.0 on 2023-05-04 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_country_alter_city_name_alter_city_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='country',
        ),
        migrations.RemoveField(
            model_name='state',
            name='country',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
