# Generated by Django 4.0 on 2023-05-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0021_property_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='payment_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
