# Generated by Django 4.0 on 2023-05-27 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0023_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='property',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='property',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='property',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='property',
            name='razorpay_payment_signature',
        ),
    ]
